version: '3'
services:
  uask:
    image: uask:0.1
    restart: unless-stopped
    container_name: uask
    ports:
      - "7999:7999"
      - "8999:8999"
    networks:
      - chain
    volumes:
      - ./uask:/uask
      - ./yu.toml:/config/yu.toml:ro
      - ./poa.toml:/config/poa.toml:ro
    depends_on:
      - meili
      - ipfs

  meili:
    image: getmeili/meilisearch:v1.2
    restart: unless-stopped
    container_name: meili
    ports:
      - "7700:7700"
    networks:
      - chain
    volumes:
      - ./meili:/data.ms

  ipfs:
    image: ipfs/go-ipfs:latest
    restart: unless-stopped
    container_name: ipfs
    volumes:
      - ./ipfs/export:/export
      - ./ipfs/data:/data/ipfs
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    networks:
      - chain

networks:
  chain:
    driver: bridge